/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedEmergencyRouteImport } from './routes/_authenticated/emergency'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin/admin.dashboard'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin/admin.users'
import { Route as AdminAdminIncidentsRouteImport } from './routes/_admin/admin.incidents'
import { Route as AuthenticatedReportNewRouteImport } from './routes/_authenticated/report.new'
import { Route as AuthenticatedReportIdSuccessRouteImport } from './routes/_authenticated/report.$id.success'
import { Route as AuthenticatedReportIdProcessingRouteImport } from './routes/_authenticated/report.$id.processing'
import { Route as AuthenticatedReportIdPreviewRouteImport } from './routes/_authenticated/report.$id.preview'
import { Route as AuthenticatedReportIdEvidenceRouteImport } from './routes/_authenticated/report.$id.evidence'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmergencyRoute = AuthenticatedEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminIncidentsRoute = AdminAdminIncidentsRouteImport.update({
  id: '/admin/incidents',
  path: '/admin/incidents',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedReportNewRoute = AuthenticatedReportNewRouteImport.update({
  id: '/report/new',
  path: '/report/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportIdSuccessRoute =
  AuthenticatedReportIdSuccessRouteImport.update({
    id: '/report/$id/success',
    path: '/report/$id/success',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportIdProcessingRoute =
  AuthenticatedReportIdProcessingRouteImport.update({
    id: '/report/$id/processing',
    path: '/report/$id/processing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportIdPreviewRoute =
  AuthenticatedReportIdPreviewRouteImport.update({
    id: '/report/$id/preview',
    path: '/report/$id/preview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportIdEvidenceRoute =
  AuthenticatedReportIdEvidenceRouteImport.update({
    id: '/report/$id/evidence',
    path: '/report/$id/evidence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/emergency': typeof AuthenticatedEmergencyRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/admin/incidents': typeof AdminAdminIncidentsRoute
  '/report/new': typeof AuthenticatedReportNewRoute
  '/report/$id/evidence': typeof AuthenticatedReportIdEvidenceRoute
  '/report/$id/preview': typeof AuthenticatedReportIdPreviewRoute
  '/report/$id/processing': typeof AuthenticatedReportIdProcessingRoute
  '/report/$id/success': typeof AuthenticatedReportIdSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/emergency': typeof AuthenticatedEmergencyRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/admin/incidents': typeof AdminAdminIncidentsRoute
  '/report/new': typeof AuthenticatedReportNewRoute
  '/report/$id/evidence': typeof AuthenticatedReportIdEvidenceRoute
  '/report/$id/preview': typeof AuthenticatedReportIdPreviewRoute
  '/report/$id/processing': typeof AuthenticatedReportIdProcessingRoute
  '/report/$id/success': typeof AuthenticatedReportIdSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/emergency': typeof AuthenticatedEmergencyRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_admin/admin/incidents': typeof AdminAdminIncidentsRoute
  '/_authenticated/report/new': typeof AuthenticatedReportNewRoute
  '/_authenticated/report/$id/evidence': typeof AuthenticatedReportIdEvidenceRoute
  '/_authenticated/report/$id/preview': typeof AuthenticatedReportIdPreviewRoute
  '/_authenticated/report/$id/processing': typeof AuthenticatedReportIdProcessingRoute
  '/_authenticated/report/$id/success': typeof AuthenticatedReportIdSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/dashboard'
    | '/emergency'
    | '/reports'
    | '/admin/dashboard'
    | '/admin/users'
    | '/admin/incidents'
    | '/report/new'
    | '/report/$id/evidence'
    | '/report/$id/preview'
    | '/report/$id/processing'
    | '/report/$id/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/dashboard'
    | '/emergency'
    | '/reports'
    | '/admin/dashboard'
    | '/admin/users'
    | '/admin/incidents'
    | '/report/new'
    | '/report/$id/evidence'
    | '/report/$id/preview'
    | '/report/$id/processing'
    | '/report/$id/success'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_admin'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/_authenticated/emergency'
    | '/_authenticated/reports'
    | '/_admin/admin/dashboard'
    | '/_admin/admin/users'
    | '/_admin/admin/incidents'
    | '/_authenticated/report/new'
    | '/_authenticated/report/$id/evidence'
    | '/_authenticated/report/$id/preview'
    | '/_authenticated/report/$id/processing'
    | '/_authenticated/report/$id/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emergency': {
      id: '/_authenticated/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof AuthenticatedEmergencyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/incidents': {
      id: '/_admin/admin/incidents'
      path: '/admin/incidents'
      fullPath: '/admin/incidents'
      preLoaderRoute: typeof AdminAdminIncidentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/report/new': {
      id: '/_authenticated/report/new'
      path: '/report/new'
      fullPath: '/report/new'
      preLoaderRoute: typeof AuthenticatedReportNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/$id/success': {
      id: '/_authenticated/report/$id/success'
      path: '/report/$id/success'
      fullPath: '/report/$id/success'
      preLoaderRoute: typeof AuthenticatedReportIdSuccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/$id/processing': {
      id: '/_authenticated/report/$id/processing'
      path: '/report/$id/processing'
      fullPath: '/report/$id/processing'
      preLoaderRoute: typeof AuthenticatedReportIdProcessingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/$id/preview': {
      id: '/_authenticated/report/$id/preview'
      path: '/report/$id/preview'
      fullPath: '/report/$id/preview'
      preLoaderRoute: typeof AuthenticatedReportIdPreviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/$id/evidence': {
      id: '/_authenticated/report/$id/evidence'
      path: '/report/$id/evidence'
      fullPath: '/report/$id/evidence'
      preLoaderRoute: typeof AuthenticatedReportIdEvidenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmergencyRoute: typeof AuthenticatedEmergencyRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedReportNewRoute: typeof AuthenticatedReportNewRoute
  AuthenticatedReportIdEvidenceRoute: typeof AuthenticatedReportIdEvidenceRoute
  AuthenticatedReportIdPreviewRoute: typeof AuthenticatedReportIdPreviewRoute
  AuthenticatedReportIdProcessingRoute: typeof AuthenticatedReportIdProcessingRoute
  AuthenticatedReportIdSuccessRoute: typeof AuthenticatedReportIdSuccessRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmergencyRoute: AuthenticatedEmergencyRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedReportNewRoute: AuthenticatedReportNewRoute,
  AuthenticatedReportIdEvidenceRoute: AuthenticatedReportIdEvidenceRoute,
  AuthenticatedReportIdPreviewRoute: AuthenticatedReportIdPreviewRoute,
  AuthenticatedReportIdProcessingRoute: AuthenticatedReportIdProcessingRoute,
  AuthenticatedReportIdSuccessRoute: AuthenticatedReportIdSuccessRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIncidentsRoute: typeof AdminAdminIncidentsRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIncidentsRoute: AdminAdminIncidentsRoute,
}

const AdminRouteRouteWithChildren =
  AdminRouteRoute._addFileChildren(AdminRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()